#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH

SBT_PATH=$OPENSHIFT_DATA_DIR/sbt
SBT_DIR=$OPENSHIFT_DATA_DIR/.sbt
IVY_DIR=$OPENSHIFT_DATA_DIR/.ivy

cd $OPENSHIFT_REPO_DIR

nohup java -jar ./target/scala-2.10/planning-poker-runnable.jar ${OPENSHIFT_DIY_IP} 8080 8000 < /dev/null > ${OPENSHIFT_DIY_LOG_DIR}server.log 2>&1 &
